### PR TITLE
WIP: client/status: add duration estimation

### LINKED ISSUE #98: status subcommand: duration estimation

### PR DESCRIPTION
**Pull request by MAFLO321**
```
Job: pull_monitor
    Type: pull
    Replication:
        Attempt #1
        Status: fan-out-filesystems
        Progress: [=======|-------------------------------------------] 46.0 MiB / 295.8 MiB @ 5.3 MiB/s 10d  5h  0m  23s remaining
          rpool                 STEPPING (step 1/12, 624 B/7.3 KiB) next: @zrepl_20200122_170738_000 => @zrepl_20200122_170811_000 (encrypted=sender-dependent)
          rpool/data            STEPPING (step 1/12, 624 B/7.3 KiB) next: @zrepl_20200122_170740_000 => @zrepl_20200122_170812_000 (encrypted=sender-dependent)
          rpool/data/postgresql STEPPING (step 1/11, 46.0 MiB/295.8 MiB) next: @zrepl_20200122_170741_000 => @zrepl_20200122_170807_000 (encrypted=sender-dependent)
    Pruning Sender:
        ...
    Pruning Receiver:
        ...
```

This will
fix #98

### CODE REVIEW

**Comment by MAFLO321** [comment]
I have already cherry-pick and tested on top of #259 on my system.
So i can rebase on top of the PR if you'd linke to merge #259 before this PR.

**Comment by problame** [comment]
Thanks for this PR!

```
        Progress: [=======|-------------------------------------------] 46.0 MiB / 295.8 MiB @ 5.3 MiB/s 10d  5h  0m  23s remaining
```

I think putting the duration estimation into parentheses would help distinguish it visually from the sending rate unit (`MiB/s`).

@antonxy I think you asked for this feature originally, and I think you wanted an estimate of the *current step's* remaining duration in addition to a total estimate.
I think your use case for that second estimate was "when can I close my laptop without losing progress?".
But since #259 will bring resumable send & recv, will that be relevant?
If so, where would be good place to put such an estimate in the output?

We currently do not have an indicator for which filesystems are `active`, although the client-side code is already prepared for that. So I guess we'd need to determine activity based on `rate != 0`.

**Comment by MAFLO321** [comment]
- added the parentheses
- remove leading space if first time only has one digit inside the parentheses (e.g. " 5h 10m  3s" -> "5h 10m  3s")

**Comment by antonxy** [comment]
> @antonxy I think you asked for this feature originally, and I think you wanted an estimate of the _current step's_ remaining duration in addition to a total estimate.
> I think your use case for that second estimate was "when can I close my laptop without losing progress?".
> But since #259 will bring resumable send & recv, will that be relevant?

Yes, that was my usecase, so with resumable send & recv I don't think it's necessary to add a remaining duration for the current step.

**Comment by problame** [comment]
@MAFLO321 thanks for your work!

**Pull request merged**
