### PR TITLE
address new rpc in package replication & pruner

### LINKED ISSUE #123: pruner exits on filesystem-local errors
Original report in https://github.com/zrepl/zrepl/issues/70#issuecomment-466814052

> As of 0.1.0-rc3, in a pull-job, **the whole pruning phase fails** (for the remaining filesystems as well!), because zrepl can not get the replication cursor bookmark for the deleted filesystem. Left me with 25000 unpruned snapshots, until I found out.
> 
> In my specific case, I'm replicating my Proxmox VMs hard disks every 10 minutes. Each VM hard disk is a zvol and therefore a separate dataset. Removing a VM and it's hard disk in Proxmox eliminates the dataset, including snapshots and bookmarks. Consequently, zrepl runs into trouble, because it can't find the cursor bookmark anymore - and aborts the whole pruning process with a PermErr.
> 
> In my case, I would expect the existing snapshots to remain on the receiver side and to be pruned according to the pruning sieves. That would leave me with some backups until the period defined in the last pruning sieve.

I think I spotted a similar issue on my test setup: https://github.com/zrepl/zrepl/pull/111#issuecomment-458074582

### PR DESCRIPTION
**Pull request by problame**
This refactoring is mandated and enabled by #111 
Development happened in #125 

## Overview

* replication
  * separate the following 2 concerns:
    * doing the actual replication steps (package replication/logic)
    * driving the application, handling errors, responding to report requests from the CLI
* pruner
  * drop broken retry mechanism (grpc errors are classified incorrectly)
  - [x] drive-by fix #123  and #126 
  * omit a new retry mechanism for now, not as important as getting 0.1 out
* churn
  - [x] zrepl status improvements
  - [x] various rpc fixes
    - [x] goroutine leak fixed
  - [x] Travis config refactorings

## Todo

- [x] Adjust README.md project structure (also wrt #111 )
- [ ] Adjust user docs screen recording => asciinema ? -> postponed to #149 
- [x] mention automatic retries in features overview
- [x] get rid of `util/watchdog`

### CODE REVIEW

**Comment by problame** [comment]
@jbliesener would you mind trying this branch against the problems described in [this comment]( https://github.com/zrepl/zrepl/issues/126#issuecomment-468912485)?

**Comment by jbliesener** [comment]
Big patch. OK, I'll give it a try when the travis job terminates. Will there be any x86_64 binary that I can run directly or will I have to build?

**Comment by problame** [comment]
> Big patch. OK, I'll give it a try when the travis job terminates. Will there be any x86_64 binary that I can run directly or will I have to build?

See link above (edited).

**Comment by JMoVS** [comment]
I will try to do some stuff on the weekend. Thx for following up!

**Comment by Debilski** [comment]
Hi, I was testing the above snapshot last week (freebsd) and it indeed solves a lot of problems that we had with a previous version (no more checksum errors after a few GB). But after a manual `zrepl signal wakeup` of a push job, I saw dozens (?) of `zfs send` jobs showing up in `htop` at the same time driving up the load and eventually crashing the server. Is this a deliberate behaviour that it starts so many sends at once?

**Pull request merged**
