### PR TITLE
Change suggested metrics port

### LINKED ISSUE #444: prometheus exporter: use better default port number & maybe consider registering it
Current documentation suggests using port `9091`, but that is the port that Prometheus server uses, I don't think that a good default to suggest for a single export client.

You could register a "default port" [in this page](https://github.com/prometheus/prometheus/wiki/Default-port-allocations), so that all `zrepl` installs can have a standard value to use.

### PR DESCRIPTION
**Pull request by lapo-luchini**
Closes #444.

### CODE REVIEW

**Review by InsanePrawn — APPROVED** [review]
Cool, thanks for taking care of registering the port with the prometheus project as well!

Not sure if we also want a changelog entry for this doc change.

**Comment by InsanePrawn** [comment]
I found a couple of additional references to the old port and decided it was quickest to just fix them, I've taken the liberty of pushing my additions with an enhanced commit message to your branch.

**Comment by problame** [comment]
Thanks for getting this done!

**Comment by problame** [comment]
committed in https://github.com/zrepl/zrepl/commit/3b5a1a8b9a14c167d1af3ab7af115d5f9ffe9c2f

**Pull request closed without merging**
