### PR TITLE
treat empty `jobs` & empty YAML as valid & ship empty `jobs` in deb/rpm

### PR DESCRIPTION
**Pull request by problame**
fixes https://github.com/zrepl/zrepl/issues/784
obsoletes https://github.com/zrepl/zrepl/pull/787

### CODE REVIEW

**Comment by problame** [comment]
@maiux and @mjasnik : please try the `.deb` that will fall out of this build pipeline: https://app.circleci.com/pipelines/github/zrepl/zrepl/7688/workflows/0e2c9dcd-d729-4a4d-a9e5-6a45797ba7f7

Steps you should try (save your config first!)

* `apt purge zrepl`
* reproduce the issue with the current release deb
  * download it from the GitHub release page
* `apt purge zrepl` again to clean up
* ensure the issue is fixed by this PR
  * download the deb from above pipeline
  * `apt install ./path/to/deb/from/pipeline`
* report back here

**Comment by Mjasnik** [comment]
If I may add... to config file shipment in general :)

As a user, I'm very much of a proponent of effective / pre-filled config files, i.e. a config file is shipped with samples commented out or disabled.
That way, I as a user can just copy/paste the config lines or un-comment the lines, adjust them to my needs and forget about it, otherwise I need to either deep dive into what's what or search the internet for supposedly working samples.

**Comment by Mjasnik** [comment]
> @maiux and @Mjasnik : please try the `.deb` that will fall out of this build pipeline: https://app.circleci.com/pipelines/github/zrepl/zrepl/7688/workflows/0e2c9dcd-d729-4a4d-a9e5-6a45797ba7f7
>     * report back here

Seems to be working fine for me.

**Comment by problame** [comment]
> As a user, I'm very much of a proponent of effective / pre-filled config files, i.e. a config file is shipped with samples commented out or disabled.
That way, I as a user can just copy/paste the example and/or un-comment the lines, adjust them to my needs and forget about it, otherwise I need to either deep dive into what's what or search the internet for supposedly working samples.

I fear we won't agree on that :)

> Seems to be working fine for me.

Great, let's merge this \o/

**Comment by maiux** [comment]
Thanks, seems to work fine

**Comment by Mikesco3** [comment]
I'm having the same problem trying to install zrepl in proxmox:
```
Setting up zrepl (0.6.1-2) ...
Created symlink /etc/systemd/system/multi-user.target.wants/zrepl.service → /lib/systemd/system/zrepl.service.
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 145.
```

I can't figure out how to download the deb file from 
[https://app.circleci.com/pipelines/github/zrepl/zrepl/7688/workflows/0e2c9dcd-d729-4a4d-a9e5-6a45797ba7f7](https://app.circleci.com/pipelines/github/zrepl/zrepl/7688/workflows/0e2c9dcd-d729-4a4d-a9e5-6a45797ba7f7)

___
So far I tried 
- the original install method from the docs... 
- then when that didn't work, ran the `apt purge zrepl`
- downloaded latest deb file from the github realease `zrepl_0.6.1-2_amd64.deb` 
- and tried to install it via `dpkg -i ./zrepl_0.6.1-2_amd64.deb`

And I'm getting the same error that I posted above...

**Pull request merged**
